Traceback (most recent call last):
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
stats.ttest_rel(y, x)[1]/2
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[23], line 1[0m
[0;32m----> 1[0m [43mstats[49m[38;5;241;43m.[39;49m[43mttest_rel[49m[43m([49m[43my[49m[43m,[49m[43m [49m[43mx[49m[43m)[49m[[38;5;241m1[39m][38;5;241m/[39m[38;5;241m2[39m

File [0;32m/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/scipy/stats/_axis_nan_policy.py:531[0m, in [0;36m_axis_nan_policy_factory.<locals>.axis_nan_policy_decorator.<locals>.axis_nan_policy_wrapper[0;34m(***failed resolving arguments***)[0m
[1;32m    529[0m [38;5;28;01mif[39;00m sentinel:
[1;32m    530[0m     samples [38;5;241m=[39m _remove_sentinel(samples, paired, sentinel)
[0;32m--> 531[0m res [38;5;241m=[39m [43mhypotest_fun_out[49m[43m([49m[38;5;241;43m*[39;49m[43msamples[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m
[1;32m    532[0m res [38;5;241m=[39m result_to_tuple(res)
[1;32m    533[0m res [38;5;241m=[39m _add_reduced_axes(res, reduced_axes, keepdims)

File [0;32m/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/scipy/stats/_stats_py.py:7707[0m, in [0;36mttest_rel[0;34m(a, b, axis, nan_policy, alternative)[0m
[1;32m   7705[0m nb [38;5;241m=[39m _get_len(b, axis, [38;5;124m"[39m[38;5;124msecond argument[39m[38;5;124m"[39m)
[1;32m   7706[0m [38;5;28;01mif[39;00m na [38;5;241m!=[39m nb:
[0;32m-> 7707[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m'[39m[38;5;124munequal length arrays[39m[38;5;124m'[39m)
[1;32m   7709[0m [38;5;28;01mif[39;00m na [38;5;241m==[39m [38;5;241m0[39m [38;5;129;01mor[39;00m nb [38;5;241m==[39m [38;5;241m0[39m:
[1;32m   7710[0m     [38;5;66;03m# _axis_nan_policy decorator ensures this only happens with 1d input[39;00m
[1;32m   7711[0m     NaN [38;5;241m=[39m _get_nan(a, b)

[0;31mValueError[0m: unequal length arrays

