Traceback (most recent call last):
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# HIDE CODE
from scipy.stats import norm
import numpy as np
from matplotlib import pyplot as plt

# Nomal com mÃ©dia = 75 e desvio padrÃ£o = 2
# Com barra horizontal na escala z
# simular valores dentro da distribuiÃ§Ã£o normal N(0,1)
x=np.linspace(0-3*1, 0+3*1,1000)

Z = norm(75,2)

# simular valores dentro da distribuiÃ§Ã£o normal N(0,1)
x=np.linspace(75-3*2, 75+3*2,1000)

ax1 = plt.subplot(1,1,1)

ax1.plot(x, Z.pdf(x), color='b')
ax1.set_xlabel('Nota')
ax1.set_ylabel('Densidade')
ax1.set_title('DistribuiÃ§Ã£o de notas')
#plt.grid(True)

# Set scond x-axis
ax2 = ax1.twiny()

# Decide the ticklabel position in the new x-axis,
# then convert them to the position in the old x-axis
newlabel = [-2.5,-2,-1,0,1,2.5] # labels of the xticklabels: the position in the new x-axis
k2degc = lambda x: (x*2)+75 # convert function: from Kelvin to Degree Celsius
newpos   = [k2degc(t) for t in newlabel]   # position of the xticklabels in the old x-axis
ax2.set_xticks(newpos)
ax2.set_xticklabels(newlabel)

ax2.xaxis.set_ticks_position('bottom') # set the position of the second x-axis to bottom
ax2.xaxis.set_label_position('bottom') # set the position of the second x-axis to bottom
ax2.spines['bottom'].set_position(('outward', 36))
ax2.set_xlabel('Escala Z')
ax2.set_xlim(ax1.get_xlim())

# Save the figure
#plt.savefig('two_xticks_under.png', bbox_inches='tight', pad_inches=0.02, dpi=150)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[4], line 2[0m
[1;32m      1[0m [38;5;66;03m# HIDE CODE[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstats[39;00m [38;5;28;01mimport[39;00m norm
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt

[0;31mModuleNotFoundError[0m: No module named 'scipy'

