Traceback (most recent call last):
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/mnt/home/rsilva/Documents/miniconda3/envs/bioestats/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# HIDE CODE
# simular valores dentro da distribuiÃ§Ã£o t
import numpy as np
from matplotlib import pyplot as plt
from scipy import stats
x=np.linspace(0-3*1, 0+3*1,1000)

T = stats.t(9)
tc = -T.ppf(0.05)
plt.plot(x, T.pdf(x), color='b', linestyle='dashed', 
         label=f'curva t com 10 amostras, valor crÃ­tico {round(tc, 4)}')

T = stats.t(30)
tc = -T.ppf(0.05)
plt.plot(x, T.pdf(x), color='black', label=f'curva t com 31 amostras, valor crÃ­tico {round(tc, 4)}')

T = stats.t(120)
tc = -T.ppf(0.05)
plt.plot(x, T.pdf(x), color='green', linestyle='dotted', 
         label=f'curva t com 121 amostras, valor crÃ­tico {round(tc, 4)}')

Z = stats.norm(0,1)
zc = -Z.ppf(0.05)
plt.plot(x, Z.pdf(x), color='red', linestyle='dashdot', 
        label=f'curva z normal padrÃ£o, valor crÃ­tico {round(zc, 4)}')

plt.legend(loc='upper center', bbox_to_anchor=(0, -0.05))
plt.title('A forma da distribuiÃ§Ã£o t para diferentes tamanhos amostrais.')
#plt.savefig('comp_curvas_t.png', bbox_inches='tight', pad_inches=0.02, dpi=150)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[4], line 5[0m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt
[0;32m----> 5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m [38;5;28;01mimport[39;00m stats
[1;32m      6[0m x[38;5;241m=[39mnp[38;5;241m.[39mlinspace([38;5;241m0[39m[38;5;241m-[39m[38;5;241m3[39m[38;5;241m*[39m[38;5;241m1[39m, [38;5;241m0[39m[38;5;241m+[39m[38;5;241m3[39m[38;5;241m*[39m[38;5;241m1[39m,[38;5;241m1000[39m)
[1;32m      8[0m T [38;5;241m=[39m stats[38;5;241m.[39mt([38;5;241m9[39m)

[0;31mModuleNotFoundError[0m: No module named 'scipy'

